//
//  SPSettings.h
//  SinglePic
//
//  Created by Ryan Renna on 2012-09-09.
//
//

//Static Notifications
static const NSString* NOTIFICATION_SERVER_SETTINGS_CHANGED = @"NOTIFICATION_SERVER_SETTINGS_CHANGED";
static const NSString* NOTIFICATION_CLIENT_SETTINGS_CHANGED = @"NOTIFICATION_CLIENT_SETTINGS_CHANGED";

#define PHOTO_EXPIRY_DAYS 7
#define SOUND_EFFECTS_ENABLED_DEFAULT YES
#define SAVE_TO_CAMERA_ROLL_DEFAULT YES